import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App hasini</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="italic">Hello my name is nothing</h1>
    </div>
  );
}
